export const NAV = [
  { path: '/',           labelKey: 'nav_home',       icon: 'bi-house' },
  { path: '/quran',      labelKey: 'nav_quran',      icon: 'bi-book' },
  { path: '/adhkar',     labelKey: 'nav_adhkar',     icon: 'bi-sun' },
  { path: '/duas',       labelKey: 'nav_duas',       icon: 'bi-hand-thumbs-up' },
  { path: '/hadith',     labelKey: 'nav_hadith',     icon: 'bi-journal-text' },
  { path: '/prayer',     labelKey: 'nav_prayer',     icon: 'bi-clock-history' },
  { path: '/qibla',      labelKey: 'nav_qibla',      icon: 'bi-compass' },
  { path: '/mosques',    labelKey: 'nav_mosques',    icon: 'bi-building' },
  { path: '/tasbeeh',    labelKey: 'nav_tasbeeh',    icon: 'bi-circle' },
  { path: '/names',      labelKey: 'nav_names',      icon: 'bi-stars' },
  { path: '/hajj',       labelKey: 'nav_hajj',       icon: 'bi-signpost' },
  { path: '/learn',      labelKey: 'nav_learn',      icon: 'bi-mortarboard' },
  { path: '/my-journey', labelKey: 'nav_my_journey', icon: 'bi-signpost-2' },
  { path: '/settings',   labelKey: 'nav_settings',   icon: 'bi-gear' },
];