export interface DivineName {
  id: number;
  name: string;
  meaning: string;
  transliteration: string;
  meaningEn: string;
}

export const NAMES_OF_ALLAH: DivineName[] = [
  { id: 1,  name: 'الرَّحْمَن',           transliteration: 'Ar-Rahman',        meaning: 'ذو الرحمة الواسعة التي وسعت كل شيء.',           meaningEn: 'The Most Compassionate — whose mercy encompasses all things.' },
  { id: 2,  name: 'الرَّحِيم',           transliteration: 'Ar-Rahim',         meaning: 'الذي يرحم المؤمنين برحمة خاصة.',                meaningEn: 'The Most Merciful — who shows special mercy to the believers.' },
  { id: 3,  name: 'الْمَلِك',            transliteration: 'Al-Malik',         meaning: 'المالك المتصرف في ملكه كيف يشاء.',              meaningEn: 'The King — the sovereign who disposes of His kingdom as He wills.' },
  { id: 4,  name: 'الْقُدُّوس',          transliteration: 'Al-Quddus',        meaning: 'المنزّه عن كل نقص وعيب.',                       meaningEn: 'The Most Holy — free from every imperfection and flaw.' },
  { id: 5,  name: 'السَّلَام',           transliteration: 'As-Salam',         meaning: 'السالم من كل عيب، ومنه السلام.',                meaningEn: 'The Source of Peace — free from every defect, from Him comes peace.' },
  { id: 6,  name: 'الْمُؤْمِن',          transliteration: 'Al-Mu\'min',       meaning: 'الذي يؤمّن خلقه من ظلمه.',                      meaningEn: 'The Granter of Security — who grants safety from His justice.' },
  { id: 7,  name: 'الْمُهَيْمِن',        transliteration: 'Al-Muhaymin',      meaning: 'الرقيب على كل شيء، الحافظ له.',                 meaningEn: 'The Guardian — who watches over and protects all things.' },
  { id: 8,  name: 'الْعَزِيز',           transliteration: 'Al-Aziz',          meaning: 'الغالب الذي لا يُغلَب.',                        meaningEn: 'The Almighty — the conqueror who is never overcome.' },
  { id: 9,  name: 'الْجَبَّار',          transliteration: 'Al-Jabbar',        meaning: 'الذي يجبر الكسير ويصلح الأمور.',                meaningEn: 'The Compeller — who mends the broken and rectifies all affairs.' },
  { id: 10, name: 'الْمُتَكَبِّر',       transliteration: 'Al-Mutakabbir',    meaning: 'المتعالي عن صفات الخلق.',                       meaningEn: 'The Supreme — who is exalted above the attributes of creation.' },
  { id: 11, name: 'الْخَالِق',           transliteration: 'Al-Khaliq',        meaning: 'الذي خلق كل شيء وقدّره.',                       meaningEn: 'The Creator — who creates all things and ordains them.' },
  { id: 12, name: 'الْبَارِئ',           transliteration: 'Al-Bari\'',        meaning: 'المنشئ للخلق بريئًا من التفاوت.',               meaningEn: 'The Originator — who brings creation into being free of discrepancy.' },
  { id: 13, name: 'الْمُصَوِّر',         transliteration: 'Al-Musawwir',      meaning: 'الذي صوّر الخلق كيف شاء.',                      meaningEn: 'The Fashioner — who shapes creation however He wills.' },
  { id: 14, name: 'الْغَفَّار',          transliteration: 'Al-Ghaffar',       meaning: 'كثير المغفرة لعباده.',                          meaningEn: 'The Ever-Forgiving — who abundantly forgives His servants.' },
  { id: 15, name: 'الْقَهَّار',          transliteration: 'Al-Qahhar',        meaning: 'الغالب على كل شيء بقهره.',                      meaningEn: 'The Subduer — who prevails over all things by His power.' },
  { id: 16, name: 'الْوَهَّاب',          transliteration: 'Al-Wahhab',        meaning: 'كثير العطاء بلا مقابل.',                        meaningEn: 'The Bestower — who gives abundantly without recompense.' },
  { id: 17, name: 'الرَّزَّاق',          transliteration: 'Ar-Razzaq',        meaning: 'الذي يرزق كل مخلوق.',                           meaningEn: 'The Provider — who sustains every creature.' },
  { id: 18, name: 'الْفَتَّاح',          transliteration: 'Al-Fattah',        meaning: 'الذي يفتح أبواب الرحمة والرزق.',                meaningEn: 'The Opener — who opens the doors of mercy and provision.' },
  { id: 19, name: 'الْعَلِيم',           transliteration: 'Al-Alim',          meaning: 'المحيط بكل شيء علمًا.',                         meaningEn: 'The All-Knowing — whose knowledge encompasses everything.' },
  { id: 20, name: 'الْقَابِض',           transliteration: 'Al-Qabid',         meaning: 'الذي يقبض الرزق والأرواح بحكمته.',              meaningEn: 'The Withholder — who withholds provision and souls by His wisdom.' },
  { id: 21, name: 'الْبَاسِط',           transliteration: 'Al-Basit',         meaning: 'الذي يبسط الرزق لمن يشاء.',                     meaningEn: 'The Extender — who extends provision to whom He wills.' },
  { id: 22, name: 'الْخَافِض',           transliteration: 'Al-Khafid',        meaning: 'الذي يخفض المتكبرين.',                          meaningEn: 'The Abaser — who humbles the arrogant.' },
  { id: 23, name: 'الرَّافِع',           transliteration: 'Ar-Rafi\'',        meaning: 'الذي يرفع أولياءه بالطاعة.',                    meaningEn: 'The Exalter — who elevates His friends through obedience.' },
  { id: 24, name: 'الْمُعِزّ',           transliteration: 'Al-Mu\'izz',       meaning: 'الذي يعز من يشاء من عباده.',                    meaningEn: 'The Honourer — who honours whomever He wills among His servants.' },
  { id: 25, name: 'الْمُذِلّ',           transliteration: 'Al-Mudhill',       meaning: 'الذي يذل من يشاء بعدله.',                       meaningEn: 'The Dishonourer — who humbles whomever He wills in justice.' },
  { id: 26, name: 'السَّمِيع',           transliteration: 'As-Sami\'',        meaning: 'الذي يسمع كل صوت.',                             meaningEn: 'The All-Hearing — who hears every sound.' },
  { id: 27, name: 'الْبَصِير',           transliteration: 'Al-Basir',         meaning: 'الذي يرى كل شيء.',                              meaningEn: 'The All-Seeing — who sees all things.' },
  { id: 28, name: 'الْحَكَم',            transliteration: 'Al-Hakam',         meaning: 'الذي يحكم بالعدل ولا يُرد حكمه.',               meaningEn: 'The Judge — who judges with justice and whose judgment is final.' },
  { id: 29, name: 'الْعَدْل',            transliteration: 'Al-\'Adl',         meaning: 'الذي لا يجور في حكمه.',                         meaningEn: 'The Just — who never acts unjustly in His ruling.' },
  { id: 30, name: 'اللَّطِيف',           transliteration: 'Al-Latif',         meaning: 'البَرّ بعباده، العالم بدقائق الأمور.',          meaningEn: 'The Subtle — kind to His servants, aware of the finest details.' },
  { id: 31, name: 'الْخَبِير',           transliteration: 'Al-Khabir',        meaning: 'العالم ببواطن الأمور.',                         meaningEn: 'The All-Aware — who knows the hidden realities.' },
  { id: 32, name: 'الْحَلِيم',           transliteration: 'Al-Halim',         meaning: 'الذي لا يعاجل بالعقوبة.',                       meaningEn: 'The Forbearing — who does not hasten punishment.' },
  { id: 33, name: 'الْعَظِيم',           transliteration: 'Al-\'Azim',        meaning: 'ذو العظمة في ذاته وصفاته.',                     meaningEn: 'The Magnificent — possessing greatness in His essence and attributes.' },
  { id: 34, name: 'الْغَفُور',           transliteration: 'Al-Ghafur',        meaning: 'الذي يغفر الذنوب جميعًا.',                      meaningEn: 'The Ever-Forgiving — who forgives all sins.' },
  { id: 35, name: 'الشَّكُور',           transliteration: 'Ash-Shakur',       meaning: 'الذي يجزي بالقليل الكثير.',                     meaningEn: 'The Most Appreciative — who rewards a little with much.' },
  { id: 36, name: 'الْعَلِيّ',           transliteration: 'Al-\'Aliyy',       meaning: 'المتعالي بذاته وقدره عن كل شيء.',               meaningEn: 'The Most High — exalted in His essence and power above all things.' },
  { id: 37, name: 'الْكَبِير',           transliteration: 'Al-Kabir',         meaning: 'الكبير الذي كل شيء دونه صغير.',                 meaningEn: 'The Most Great — before whom everything else is small.' },
  { id: 38, name: 'الْحَفِيظ',           transliteration: 'Al-Hafiz',         meaning: 'الحافظ لعباده ولأعمالهم.',                      meaningEn: 'The Preserver — who protects His servants and their deeds.' },
  { id: 39, name: 'الْمُقِيت',           transliteration: 'Al-Muqit',         meaning: 'الذي يخلق الأقوات ويوصلها للخلق.',               meaningEn: 'The Sustainer — who creates and delivers provisions to creation.' },
  { id: 40, name: 'الْحَسِيب',           transliteration: 'Al-Hasib',         meaning: 'الكافي عباده، المحاسب لهم.',                    meaningEn: 'The Reckoner — sufficient for His servants and their reckoning.' },
  { id: 41, name: 'الْجَلِيل',           transliteration: 'Al-Jalil',         meaning: 'ذو الجلال والعظمة.',                            meaningEn: 'The Majestic — possessing majesty and grandeur.' },
  { id: 42, name: 'الْكَرِيم',           transliteration: 'Al-Karim',         meaning: 'كثير الخير، عظيم العطاء.',                      meaningEn: 'The Most Generous — abundant in good and magnificent in giving.' },
  { id: 43, name: 'الرَّقِيب',           transliteration: 'Ar-Raqib',         meaning: 'المراقب لأحوال خلقه.',                          meaningEn: 'The Watchful — who observes the states of His creation.' },
  { id: 44, name: 'الْمُجِيب',           transliteration: 'Al-Mujib',         meaning: 'الذي يجيب دعاء الداعين.',                       meaningEn: 'The Responsive — who answers the call of those who supplicate.' },
  { id: 45, name: 'الْوَاسِع',           transliteration: 'Al-Wasi\'',        meaning: 'الواسع في علمه ورحمته.',                        meaningEn: 'The All-Encompassing — vast in knowledge and mercy.' },
  { id: 46, name: 'الْحَكِيم',           transliteration: 'Al-Hakim',         meaning: 'ذو الحكمة البالغة في خلقه وأمره.',              meaningEn: 'The All-Wise — possessing perfect wisdom in His creation and command.' },
  { id: 47, name: 'الْوَدُود',           transliteration: 'Al-Wadud',         meaning: 'المحب لأنبيائه وأوليائه.',                      meaningEn: 'The Most Loving — who loves His prophets and righteous servants.' },
  { id: 48, name: 'الْمَجِيد',           transliteration: 'Al-Majid',         meaning: 'ذو الشرف والعزّ والكرم.',                       meaningEn: 'The Most Glorious — possessing honour, might, and generosity.' },
  { id: 49, name: 'الْبَاعِث',           transliteration: 'Al-Ba\'ith',       meaning: 'الذي يبعث الخلق يوم القيامة.',                  meaningEn: 'The Resurrector — who raises creation on the Day of Judgment.' },
  { id: 50, name: 'الشَّهِيد',           transliteration: 'Ash-Shahid',       meaning: 'الشاهد على كل شيء، لا يغيب عنه شيء.',           meaningEn: 'The Witness — witness to all things, nothing escapes Him.' },
  { id: 51, name: 'الْحَقّ',             transliteration: 'Al-Haqq',          meaning: 'الثابت الذي لا يزول.',                          meaningEn: 'The Truth — the abiding who never ceases to be.' },
  { id: 52, name: 'الْوَكِيل',           transliteration: 'Al-Wakil',         meaning: 'القائم بمصالح عباده، الكفيل بهم.',              meaningEn: 'The Trustee — who manages the affairs of His servants and guarantees them.' },
  { id: 53, name: 'الْقَوِيّ',           transliteration: 'Al-Qawiyy',        meaning: 'ذو القوة المتين الذي لا يعجزه شيء.',            meaningEn: 'The Most Strong — whose firm strength nothing can overcome.' },
  { id: 54, name: 'الْمَتِين',           transliteration: 'Al-Matin',         meaning: 'الشديد القوي الذي لا تنقطع قوته.',              meaningEn: 'The Firm — the strong whose strength never ends.' },
  { id: 55, name: 'الْوَلِيّ',           transliteration: 'Al-Waliyy',        meaning: 'الناصر المتولي أمور عباده.',                    meaningEn: 'The Protecting Friend — the helper who manages His servants\' affairs.' },
  { id: 56, name: 'الْحَمِيد',           transliteration: 'Al-Hamid',         meaning: 'المحمود على كل حال.',                           meaningEn: 'The Praiseworthy — worthy of praise in every state.' },
  { id: 57, name: 'الْمُحْصِي',          transliteration: 'Al-Muhsi',         meaning: 'الذي أحصى كل شيء عددًا.',                       meaningEn: 'The Reckoner of All — who has counted everything precisely.' },
  { id: 58, name: 'الْمُبْدِئ',          transliteration: 'Al-Mubdi\'',       meaning: 'الذي بدأ الخلق وابتدعه.',                       meaningEn: 'The Originator — who began creation and brought it into being.' },
  { id: 59, name: 'الْمُعِيد',           transliteration: 'Al-Mu\'id',        meaning: 'الذي يعيد الخلق بعد الفناء.',                   meaningEn: 'The Restorer — who returns creation after its passing.' },
  { id: 60, name: 'الْمُحْيِي',          transliteration: 'Al-Muhyi',         meaning: 'الذي يمنح الحياة ويُحيي الموتى.',                meaningEn: 'The Giver of Life — who grants life and revives the dead.' },
  { id: 61, name: 'الْمُمِيت',           transliteration: 'Al-Mumit',         meaning: 'الذي يقضي بالموت على من يشاء.',                 meaningEn: 'The Bringer of Death — who decrees death upon whom He wills.' },
  { id: 62, name: 'الْحَيّ',             transliteration: 'Al-Hayy',          meaning: 'الحي حياة كاملة لا يعتريها فناء.',              meaningEn: 'The Ever-Living — whose perfect life is untouched by death.' },
  { id: 63, name: 'الْقَيُّوم',          transliteration: 'Al-Qayyum',        meaning: 'القائم بنفسه المقيم لغيره.',                    meaningEn: 'The Self-Subsisting — who sustains Himself and sustains all others.' },
  { id: 64, name: 'الْوَاجِد',           transliteration: 'Al-Wajid',         meaning: 'الذي لا يعجزه شيء، ولا يفقد ما يريد.',          meaningEn: 'The Finder — who is never incapable of anything and never loses what He wills.' },
  { id: 65, name: 'الْمَاجِد',           transliteration: 'Al-Majid',         meaning: 'ذو المجد والكرم.',                              meaningEn: 'The Noble — possessing glory and generosity.' },
  { id: 66, name: 'الْوَاحِد',           transliteration: 'Al-Wahid',         meaning: 'المتوحد بالأحدية لا شريك له.',                  meaningEn: 'The One — unique in oneness with no partner.' },
  { id: 67, name: 'الْأَحَد',            transliteration: 'Al-Ahad',          meaning: 'الفرد الذي لا نظير له.',                        meaningEn: 'The Unique — the indivisible who has no equal.' },
  { id: 68, name: 'الصَّمَد',            transliteration: 'As-Samad',         meaning: 'السيد المقصود في الحوائج.',                     meaningEn: 'The Eternal — the Master to whom all turn in need.' },
  { id: 69, name: 'الْقَادِر',           transliteration: 'Al-Qadir',         meaning: 'القادر على كل شيء.',                            meaningEn: 'The Capable — who is able to do all things.' },
  { id: 70, name: 'الْمُقْتَدِر',        transliteration: 'Al-Muqtadir',      meaning: 'التام القدرة، لا يفوته شيء.',                   meaningEn: 'The Omnipotent — perfect in power, nothing escapes Him.' },
  { id: 71, name: 'الْمُقَدِّم',         transliteration: 'Al-Muqaddim',      meaning: 'الذي يقدّم من يشاء من خلقه.',                   meaningEn: 'The Expediter — who advances whom He wills among His creation.' },
  { id: 72, name: 'الْمُؤَخِّر',         transliteration: 'Al-Mu\'akhkhir',   meaning: 'الذي يؤخّر ما يشاء بحكمته.',                    meaningEn: 'The Delayer — who delays what He wills in His wisdom.' },
  { id: 73, name: 'الْأَوَّل',           transliteration: 'Al-Awwal',         meaning: 'الذي ليس قبله شيء.',                            meaningEn: 'The First — before whom there is nothing.' },
  { id: 74, name: 'الْآخِر',            transliteration: 'Al-Akhir',         meaning: 'الذي ليس بعده شيء.',                            meaningEn: 'The Last — after whom there is nothing.' },
  { id: 75, name: 'الظَّاهِر',           transliteration: 'Az-Zahir',         meaning: 'الظاهر بأدلته فوق كل شيء.',                     meaningEn: 'The Manifest — evident through His signs above all things.' },
  { id: 76, name: 'الْبَاطِن',           transliteration: 'Al-Batin',         meaning: 'العالم بالخفيات، القريب من عباده.',             meaningEn: 'The Hidden — knower of hidden things, close to His servants.' },
  { id: 77, name: 'الْوَالِي',           transliteration: 'Al-Wali',          meaning: 'المالك المتصرف في كل شيء.',                     meaningEn: 'The Governor — the owner who disposes of all things.' },
  { id: 78, name: 'الْمُتَعَالِي',       transliteration: 'Al-Muta\'ali',     meaning: 'المتعالي عن كل نقص وعيب.',                      meaningEn: 'The Most Exalted — beyond every imperfection and flaw.' },
  { id: 79, name: 'الْبَرّ',             transliteration: 'Al-Barr',          meaning: 'المحسن لعباده، الواسع في برّه.',                meaningEn: 'The Source of All Goodness — benevolent to His servants, vast in kindness.' },
  { id: 80, name: 'التَّوَّاب',          transliteration: 'At-Tawwab',        meaning: 'الذي يقبل توبة التائبين.',                      meaningEn: 'The Acceptor of Repentance — who accepts the repentance of the penitent.' },
  { id: 81, name: 'الْمُنْتَقِم',        transliteration: 'Al-Muntaqim',      meaning: 'الذي ينتقم من الظالمين بعدله.',                 meaningEn: 'The Avenger — who takes vengeance on the unjust in justice.' },
  { id: 82, name: 'الْعَفُوّ',           transliteration: 'Al-\'Afuww',       meaning: 'الذي يعفو عن السيئات.',                         meaningEn: 'The Pardoner — who pardons wrongdoings.' },
  { id: 83, name: 'الرَّءُوف',           transliteration: 'Ar-Ra\'uf',        meaning: 'شديد الرحمة بعباده.',                           meaningEn: 'The Most Kind — intensely merciful to His servants.' },
  { id: 84, name: 'مَالِكُ الْمُلْك',    transliteration: 'Malik al-Mulk',    meaning: 'المتصرف في ملكه كيف يشاء.',                     meaningEn: 'Master of the Kingdom — who disposes of His dominion as He wills.' },
  { id: 85, name: 'ذُو الْجَلَالِ وَالْإِكْرَام', transliteration: 'Dhul-Jalali wal-Ikram', meaning: 'ذو العظمة والكرم والجلال.',              meaningEn: 'Lord of Majesty and Honour — possessing majesty, generosity, and glory.' },
  { id: 86, name: 'الْمُقْسِط',          transliteration: 'Al-Muqsit',        meaning: 'العادل في حكمه، المنصف للمظلوم.',               meaningEn: 'The Equitable — just in His judgment, granting justice to the wronged.' },
  { id: 87, name: 'الْجَامِع',           transliteration: 'Al-Jami\'',        meaning: 'الذي يجمع الخلائق ليوم الحساب.',                meaningEn: 'The Gatherer — who gathers creation for the Day of Reckoning.' },
  { id: 88, name: 'الْغَنِيّ',           transliteration: 'Al-Ghaniyy',       meaning: 'الغني عن كل شيء، وكل شيء يحتاجه.',              meaningEn: 'The Self-Sufficient — free of all needs, while all things need Him.' },
  { id: 89, name: 'الْمُغْنِي',          transliteration: 'Al-Mughni',        meaning: 'الذي يُغني من يشاء من خلقه.',                   meaningEn: 'The Enricher — who enriches whom He wills among His creation.' },
  { id: 90, name: 'الْمَانِع',           transliteration: 'Al-Mani\'',        meaning: 'الذي يمنع بحكمته ما يشاء.',                     meaningEn: 'The Withholder — who withholds what He wills in His wisdom.' },
  { id: 91, name: 'الضَّارّ',            transliteration: 'Ad-Darr',          meaning: 'الذي يقدّر الضر بحكمته.',                       meaningEn: 'The Afflicter — who decrees harm in His wisdom.' },
  { id: 92, name: 'النَّافِع',           transliteration: 'An-Nafi\'',        meaning: 'الذي يقدّر النفع لعباده.',                      meaningEn: 'The Benefactor — who decrees benefit for His servants.' },
  { id: 93, name: 'النُّور',             transliteration: 'An-Nur',           meaning: 'الهادي، نور السماوات والأرض.',                  meaningEn: 'The Light — the Guide, light of the heavens and the earth.' },
  { id: 94, name: 'الْهَادِي',           transliteration: 'Al-Hadi',          meaning: 'الذي يهدي عباده إلى الحق.',                     meaningEn: 'The Guide — who guides His servants to the truth.' },
  { id: 95, name: 'الْبَدِيع',           transliteration: 'Al-Badi\'',        meaning: 'الخالق المبدع بلا مثال سابق.',                  meaningEn: 'The Incomparable Originator — who creates without precedent.' },
  { id: 96, name: 'الْبَاقِي',           transliteration: 'Al-Baqi',          meaning: 'الدائم الذي لا يفنى.',                          meaningEn: 'The Everlasting — the enduring who never perishes.' },
  { id: 97, name: 'الْوَارِث',           transliteration: 'Al-Warith',        meaning: 'الباقي بعد فناء الخلق، مالك كل شيء.',           meaningEn: 'The Inheritor — who remains after creation perishes, owner of all things.' },
  { id: 98, name: 'الرَّشِيد',           transliteration: 'Ar-Rashid',        meaning: 'الذي أفعاله على سنن الحكمة والرشاد.',           meaningEn: 'The Rightly-Guided — whose actions follow wisdom and guidance.' },
  { id: 99, name: 'الصَّبُور',           transliteration: 'As-Sabur',         meaning: 'الذي لا يعاجل العصاة بالعقوبة.',                meaningEn: 'The Most Patient — who does not hasten punishment for the disobedient.' },
];